### ISSUE TITLE
Startup problem

### ISSUE THREAD

**Issue by Eronn0** [YelehaUwU/3DEditor#1]
hello, I need help with using and running, when the script starts
[14:32:25] Starting 3DEditor appears
[14:32:25] WARNING: 3DEditor\server_updater.lua:17: Access denied @ 'fetchRemote' 
for any help thanks a lot

**Comment by Derbosik** [comment]
Make sure to allow fetchRemote in the ACL for 3DEditor (mods/deathmatch/acl.xml).

```
    <group name="Admin"> 
        <acl name="Moderator"></acl> 
        <acl name="SuperModerator"></acl> 
        <acl name="Admin"></acl> 
        <acl name="RPC"></acl> 
        <object name="resource.3DEditor"></object>  <---- Add this line to the bottom of the admin group, or any other group with fetchRemote permissions.
    </group>
```
(This is only example configuration, yours may differ)
